# export FZF_DEFAULT_COMMAND='rg --files --no-ignore-vcs --hidden'
# use the above setting if you want to use ripgrep to feed the files to fzf
export FZF_DEFAULT_COMMAND="fd --type f --hidden --ignore-file '$HOME/.gitignore'"
export FZF_CTRL_T_COMMAND="fd --type f --hidden --ignore-file '$HOME/.gitignore'"
export FZF_ALT_C_COMMAND="fd --type d --hidden --ignore-file '$HOME/.gitignore'"

export FZF_DEFAULT_OPTS="--multi --reverse --ansi --height 50%"

# fzf.zsh is autogenerated by fzf
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

is_in_git_repo() {
  git rev-parse HEAD > /dev/null 2>&1
}

# Preview commit diffs from git log
preview-commits() {
  is_in_git_repo || return
  git log --date=short --format="%C(green)%C(bold)%cd %C(auto)%h%d %s (%an)" --graph --color=always |
  fzf --no-sort --bind 'ctrl-s:toggle-sort,alt-p:preview-up,alt-n:preview-down' \
    --header 'Press CTRL-S to toggle sort' \
    --preview 'grep -o "[a-f0-9]\{7,\}" <<< {} | xargs git show --color=always' |
  grep -o "[a-f0-9]\{7,\}"
}

# Preview files
# (requires https://github.com/sharkdp/bat for syntax highlighting)
#
# Pipe the output of ls or fd to this function to preview the files in the search result
# Example:
#   fd -t file "search term" /path/ | fzf-preview
fzf-preview() {
    fzf --no-sort --bind 'ctrl-s:toggle-sort,alt-n:preview-down,alt-p:preview-up' \
        --header 'Press CTRL-S to toggle sort' \
        --preview 'bat --color=always {}'
}

# Preview the search results with some context lines above and below
# (requires https://github.com/sharkdp/bat for syntax highlighting)
#
# Pipe the output of `grep` or `rg` to this function to preview the file with a matching
# result. The line matching the search will be highlighted and scrolled-to in the preview
# window.
#
# Example:
#   rg --no-heading --line-number "search term" /path/ | fzf-search-preview
fzf-search-preview() {
    fzf --no-sort --delimiter=: \
        --bind 'ctrl-s:toggle-sort,alt-n:preview-down,alt-p:preview-up' \
        --preview 'file={1}; line={2}; lines=$FZF_PREVIEW_LINES; center=$(( (lines - 3) / 2 )); if [ $line -lt $center ]; then center=$line; fi; start=$(( line - center )); end=$(( lines + start )); bat --color always --highlight-line $line --line-range $start:$end --paging never "$file"'
}
